/**
 * Generate website/privacy.html and website/terms.html from docs/legal/*.md.
 *
 * docs/legal/ stays the single source of truth (the app bundles the same
 * files via `npm run legal:sync`). Run after editing either document:
 *
 *   npm run website:legal
 *
 * Handles the markdown subset those documents use: headings, paragraphs,
 * bullet lists, tables, **bold** and `code`. No dependencies.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const PAGES = [
  { source: 'docs/legal/privacy-policy.md', target: 'website/privacy.html', title: 'Privacy Policy' },
  { source: 'docs/legal/terms-of-service.md', target: 'website/terms.html', title: 'Terms of Service' },
];

const escapeHtml = (text) =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function inline(text) {
  return escapeHtml(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
    .replace(/([\w.+-]+@[\w-]+\.[\w.]+)/g, '<a href="mailto:$1">$1</a>');
}

function markdownToHtml(markdown) {
  const lines = markdown.split('\n');
  const out = [];
  let paragraph = [];
  let list = [];

  const flush = () => {
    if (paragraph.length) out.push(`<p>${inline(paragraph.join(' '))}</p>`);
    if (list.length) out.push(`<ul>\n${list.map((item) => `  <li>${inline(item)}</li>`).join('\n')}\n</ul>`);
    paragraph = [];
    list = [];
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    const heading = /^(#{1,3}) (.+)$/.exec(line);

    if (!line) {
      flush();
    } else if (heading) {
      flush();
      const level = heading[1].length;
      out.push(`<h${level}>${inline(heading[2])}</h${level}>`);
    } else if (line.startsWith('- ')) {
      if (paragraph.length) flush();
      list.push(line.slice(2));
    } else if (line.startsWith('|')) {
      flush();
      const rows = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        const cells = lines[i].trim().slice(1, -1).split('|').map((cell) => cell.trim());
        if (!cells.every((cell) => /^:?-+:?$/.test(cell))) rows.push(cells);
        i++;
      }
      i--;
      const [header, ...body] = rows;
      out.push(
        '<div class="table-wrap"><table>\n' +
          `<thead><tr>${header.map((cell) => `<th>${inline(cell)}</th>`).join('')}</tr></thead>\n` +
          `<tbody>\n${body.map((row) => `<tr>${row.map((cell) => `<td>${inline(cell)}</td>`).join('')}</tr>`).join('\n')}\n</tbody>\n` +
          '</table></div>'
      );
    } else {
      if (list.length) flush();
      paragraph.push(line);
    }
  }
  flush();
  return out.join('\n');
}

const page = (title, body) => `<!doctype html>
<!-- GENERATED by website/scripts/build-legal.mjs from docs/legal/. Do not edit by hand. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title} · BChat</title>
  <meta name="description" content="BChat ${title}.">
  <meta name="theme-color" content="#FFF8F1" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#17161F" media="(prefers-color-scheme: dark)">
  <link rel="icon" type="image/png" href="assets/favicon.png">
  <link rel="apple-touch-icon" href="assets/apple-touch-icon.png">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <nav class="container nav" aria-label="Main">
      <a class="brand" href="./"><img src="assets/logo.png" alt="" width="38" height="41">BChat</a>
      <a class="btn btn-ghost btn-small" href="./">← Back to home</a>
    </nav>
  </header>
  <main id="main" class="legal">
    <article class="container">
${body}
    </article>
  </main>
  <footer class="site-footer">
    <div class="container">
      <div class="footer-inner">
        <a class="brand" href="./"><img src="assets/logo.png" alt="" width="38" height="41">BChat</a>
        <ul class="footer-links">
          <li><a href="privacy.html">Privacy Policy</a></li>
          <li><a href="terms.html">Terms of Service</a></li>
          <li><a href="mailto:bchatdevx@gmail.com">Contact</a></li>
        </ul>
      </div>
      <p class="disclaimer">BChat is an independent student project. It is not affiliated with, sponsored by, or endorsed by the University of California, Los Angeles (UCLA) or the Regents of the University of California. © 2026 BChat.</p>
    </div>
  </footer>
</body>
</html>
`;

for (const { source, target, title } of PAGES) {
  const html = markdownToHtml(readFileSync(join(root, source), 'utf8'));
  writeFileSync(join(root, target), page(title, html));
  console.log(`Wrote ${target}`);
}
