/**
 * Copy docs/legal/*.md into the client bundle.
 *
 * The Terms of Service and Privacy Policy live in docs/legal/ (that's the
 * copy you host on the web). The app can't read files outside client/, so
 * this script writes them into client/legal/content.ts as string constants.
 *
 * Run after editing either document:
 *   npm run legal:sync
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const docs = {
  TERMS_OF_SERVICE: 'docs/legal/terms-of-service.md',
  PRIVACY_POLICY: 'docs/legal/privacy-policy.md',
};

let out =
  '// GENERATED by scripts/syncLegal.js from docs/legal/. Do not edit by hand;\n' +
  '// edit the markdown files and run `npm run legal:sync`.\n\n';

for (const [name, rel] of Object.entries(docs)) {
  const text = fs.readFileSync(path.join(root, rel), 'utf8');
  out += `export const ${name} = ${JSON.stringify(text)};\n\n`;
}

const target = path.join(root, 'client/legal/content.ts');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);
console.log(`Wrote ${path.relative(root, target)}`);
